// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzRAau9xBN892ox1IoGSoRAnF4D-pqo3c',
    appId: '1:668546138810:web:0fd29e4cb64d562d0c7883',
    messagingSenderId: '668546138810',
    projectId: 'donaition-app',
    authDomain: 'donaition-app.firebaseapp.com',
    storageBucket: 'donaition-app.firebasestorage.app',
    measurementId: 'G-V5Q08BXR7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9faTLPsBUzvX939e6BIxU-Nq6VbQGB5k',
    appId: '1:668546138810:android:fa47588e3f5084310c7883',
    messagingSenderId: '668546138810',
    projectId: 'donaition-app',
    storageBucket: 'donaition-app.firebasestorage.app',
  );
}
